---
- name: Install Grafana
  hosts: localhost
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - adduser
        - libfontconfig1
        - musl

    - name: Download Grafana deb package
      get_url:
        url: https://dl.grafana.com/oss/release/grafana_10.4.0_amd64.deb
        dest: /tmp/grafana_10.4.0_amd64.deb

    - name: Install Grafana deb package
      apt:
        deb: /tmp/grafana_10.4.0_amd64.deb
        state: present
    
    - name: Start Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes
